---
title: An Introduction to Forwards and Options
subtitle: |
  | McDonald Chapter 2
  | DATA 5695/6695
author: Tyler J. Brough
date: 2025-01-09
title-slide-attributes:
  data-background-color: "#486790"
format: 
  revealjs:
    theme: tjb.scss      # Modified simple theme.
    slide-number: c/t    # Numbered slides current/total.
    self-contained: true # Render to a single HTML file.
execute:
  eval: false
  echo: true
---

# McDonald Chapter 2: An Introduction to Forwards and Options

## Introduction 

<br>

::: {.incremental}
- Basic derivatives contracts
  - Forward contracts
  - Call options
  - Put options

- Types of positions
  - Long position
  - Short position
  
- Graphical representation
  - Payoff diagrams
  - Profit diagrams
:::


# 2.1 Forward Contracts

## Forward Contracts

<br>

::: {.incremental}
- **Forward contract**: a binding agreement (obligation) to buy/sell an underlying asset in the future, at a preset price.

- Futures contracts are the same as forwards in principle except for some institutional and pricing differences. 

- A forward contract specifiies:
  - Specifies the quantity and exact type of the asset or commodity the seller must deliver.
  - Specifies delivery logistics, such as time, date, and place. 
  - Specifies the price the buyer will pay at the time of deliver.
  - Obligates the seller to sell and the buyer to buy, subject to the above specifications.
:::

## Terminology 

<br>

::: {.incremental}
- **Expiration date**: The time at which the contract settles. 
- **Underlying asset**: The asset or commodity on which the forward contract is based.
- **Premium**: Besides bid-offer spreads, a forward contract does not require an up-front payment.
:::

## The Payoff on a Forward Contract

<br>

The **payoff** to a contract is the value of the position at expiration. 

### Long Payoff 

<br>

::: {.incremental}
- $\mbox{Payoff to long forward} = S_{T} - F_{T}$
:::

<br>

### Short Payoff 

<br>

::: {.incremental}
- $\mbox{Payoff to short forward} = F_{T} - S_{T}$
:::


## Graphing the Payoff on a Forward Contract 

```{python}
#| echo: false
#| eval: true

import numpy as np
import matplotlib.pyplot as plt
```

```{python}
#| echo: true
#| eval: true
#| output-location: column

# Spot and forward prices
spot_prices = np.arange(800.0, 1250.0, 50.0)
forward_price = 1020.0

# Calculate payoffs for long and short positions
long_payoffs = spot_prices - forward_price
short_payoffs = forward_price - spot_prices 

# Plotting the payoffs
plt.figure(figsize=(10, 6))
plt.plot(spot_prices, long_payoffs, label='Long Forward Payoff', linestyle='--', linewidth=2)
plt.plot(spot_prices, short_payoffs, label='Short Forward Payoff', linestyle='--', linewidth=2)

# Adding labels, title, and legend
plt.axhline(0, color='black', linewidth=1, linestyle='--')  # Add horizontal line at payoff = 0
plt.xlabel('Price of Underlying Asset at Maturity', fontsize=12)
plt.ylabel('Payoff', fontsize=12)
plt.title('Payoff of Forward Contract (Long and Short)', fontsize=14)
plt.legend(fontsize=10)
plt.grid(alpha=0.5)

# Show the plot
plt.show()
```

## Comparing a Forward and Outright Purchase 

<br>

::: {.incremental}
- Purchasing the S&R Index via a long forward contract is a way to purchase the asset at the date of expiration.
- **Q:** Is there any value in purchasing the index via a forward contract vs. outright purchase of the index today?
  - If we purchase the index outright it costs $\$1,000$ today (by assumption in the textbook)
  - The value of the position at expiration (6 mos) is the value of the index at that date.
- Let's graph the payoffs of both to compare.
:::

## 

```{python}
#| echo: true
#| eval: true
#| output-location: column

# Spot and forward prices
spot_prices = np.arange(0.0, 2500.0, 50.0)
forward_price = 1020.0
long_payoffs = spot_prices - forward_price

# Plotting the spot and forward positions (long)
plt.figure(figsize=(10, 6))
plt.plot(spot_prices, spot_prices, label='Long Spot Payoff', linestyle='--', linewidth=2)
plt.plot(spot_prices, long_payoffs, label='Long Forward Payoff', linestyle='--', linewidth=2)

# Adding labels, title, and legend
plt.axhline(0, color='black', linewidth=1, linestyle='--')  # Add horizontal line at payoff = 0
plt.xlabel('Value of Index at Expiration', fontsize=12)
plt.ylabel('Payoff', fontsize=12)
plt.title('Payoff of Spot and Forward Long Positions', fontsize=14)
plt.legend(fontsize=10)
plt.grid(alpha=0.5)

# Show the plot
plt.show()
```


## Additional Considerations 

<br>

::: {.incremental}
- Type of settlement
  - Cash settlement: less costly and more practical (most financial futures)
  - Physical delivery: often avoided due to significant costs 

- Credit risk of the counter party
  - Major issue for over-the-counter (OTC) contracts
    - Credit check, collateral, bank letter of credit
    - ISDA
  - Less severe for exchange-traded contracts
    - Exchange guarantees transtions, requires collateral 
::: 


# 2.2 Call Options 


## Call Options

<br> 

::: {.incremental}
- A non-binding agreement (right but not an obilgation) to buy an asset in the future, at a preset price (strike price)

- Preserves the upside potential, while at the same time elminating the unpleasant downside (for the buyer only)

- The seller of a call option (writer) is obligated to deliver if the option is exercised by the holder 
:::


## Option Terminology 

<br>

::: {.incremental}
- A call option gives the owner the right but not the obligation to buy the underlying asset at a predetermined price during a predetermined time period
  
- **Strike (exercise) price**: the amount paid by the option buyer for the asset if she decides to exercise
  
- **Exercise**: the act of paying the strike price to buy the asset 
   
- **Expiration**: the date by which the option must be exercised or expire worthless
  
- **Exercise Style**: specifies when the option can be exercised:
  - European-style: can be exercised only at expiration date
  - American-style: can be exercised at any time before expiration 
  - Bermudan-style: can be exercised during specified periods
:::

## Payoff and Profit for a Purchased Call Option 

<br>

::: {.incremental}
- $\mbox{Payoff} = \max{(0, S_{T} - K)}$

- $\mbox{Profit} = \mbox{Payoff} - FV{(C_{0})}$

- Let's look at some examples
  - S&R Index 6-month call option
    - Strike price: $\$1000$
    - Premium: $C_{0} = \$93.81$ 
    - 6-month risk free rate: $r = 2\%$ per annum 
:::


## Payoff Diagram for a (Long) Call Option 

```{python}
#| echo: true
#| eval: true
#| output-location: column

# Calculation prices, payoffs
strike = 1000.0
spot_prices = np.arange(800.0, 1250.0, 50.0)
call_payoffs = np.maximum(spot_prices - strike, 0.0)

# Plot the call payoff
plt.plot(spot_prices, call_payoffs, label='(Long) Call Payoff', linestyle='--', linewidth=2)

# Adding labels, title, and legend
plt.axhline(0, color='black', linewidth=1, linestyle='--')  # Add horizontal line at payoff = 0
plt.xlabel('Value of Index at Expiration', fontsize=12)
plt.ylabel('Payoff', fontsize=12)
plt.title('Long Call Payoff', fontsize=14)
plt.legend(fontsize=10)
plt.grid(alpha=0.5)

# Show the plot
plt.show()
```

## Profit Diagram for a (Long) Call Option

<br>

```{python}
#| echo: true
#| eval: true
#| output-location: column

# Prices, Payoffs, Strike, Premium
strike = 1000.0
call_premium = 93.81 * np.exp(0.02)
spot_prices = np.arange(800.0, 1250.0, 50.0)
call_payoffs = np.maximum(spot_prices - strike, 0.0)
call_profit = call_payoffs - call_premium
forward_price = 1020.0
long_payoffs = spot_prices - forward_price

# 
plt.figure(figsize=(10, 6))
plt.plot(spot_prices, call_profit, label='Long Call Profit', linestyle='--', linewidth=2)
plt.plot(spot_prices, long_payoffs, label='Long Forward Payoff', linestyle='--', linewidth=2)

# Adding labels, title, and legend
plt.axhline(0, color='black', linewidth=1, linestyle='--')  # Add horizontal line at payoff = 0
plt.xlabel('Value of Index at Expiration', fontsize=12)
plt.ylabel('Payoff', fontsize=12)
plt.title('(Long) Call Profit vs Long Forward Payoff', fontsize=14)
plt.legend(fontsize=10)
plt.grid(alpha=0.5)

# Show the plot
plt.show()
```

## Homework Exercise: Payoff & Profit Diagrams of Written Call Option

<br>

- See if you can adapt the code above to generate the plots for a written (short) call option position

- *Hint*: options are a zero-sum game

- Discussion


# 2.3 Put Options 


## Payoff and Profit for a Purchased Put Option 

<br>

::: {.incremental}
- A put option gives the holder the right but not the obligation to sell the underlying asset at the strike price during a preset time period
  
- The seller of a put option is obligated to buy if the holder decides to exercise 

- Payoff/Profit of a long put: 
  - $\mbox{Payoff} = \max{(0, K - S_{T})}$
  - $\mbox{Profit} = \mbox{Payoff} - FV(P_{0})$

- Payoff/Profit of a short (written) put: 
  - $\mbox{Payoff} = -\max{(0, K - S_{T})}$
  - $\mbox{Profit} = \mbox{Payoff} + FV(P_{0})$
:::

## Payoff and Profit for a Written Put Option 

- Left as a homework exercise
  

## The "Moneyness" of an Option

::: {.incremental}
- A call option becomes more profitable when the underlying asset appreciates in value

- A put option becomes more profitable when the underlying asset depreciates in value 

- Moneyness:
  - In-the-money (ITM) option: positive payoff if exercised immediately (at the prevailing spot price)
  - At-the-money (ATM) option: zero payoff if exercised immediately (at the prevailing spot price)
  - Out-of-the-money (OTM): negative payoff if exercised immediately (at the prevailing spot price)
:::